In [1]:
import mlxtend
import numpy as np
import pandas as pd

In [2]:
data = np.array([['우유', '기저귀', '쥬스'], 
               ['양상추', '기저귀', '맥주'], 
               ['우유', '양상추', '기저귀', '맥주'], 
               ['양상추', '맥주']])

In [4]:
data

array([list(['우유', '기저귀', '쥬스']), list(['양상추', '기저귀', '맥주']),
       list(['우유', '양상추', '기저귀', '맥주']), list(['양상추', '맥주'])],
      dtype=object)

## Apriori 알고리즘

In [8]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(data).transform(data) # array형태로 나타냄 T/F
df = pd.DataFrame(te_ary, columns = te.columns_)
df

     기저귀     맥주    양상추     우유     쥬스
0   True  False  False   True   True
1   True   True   True  False  False
2   True   True   True   True  False
3  False   True   True  False  False

In [16]:
%%time
# apriori 알고리즘 돌리기
from mlxtend.frequent_patterns import apriori
apriori(df, min_support = 0.5, use_colnames = True)

CPU times: user 9.47 ms, sys: 232 µs, total: 9.7 ms
Wall time: 7.99 ms

   support        itemsets
0     0.75           (기저귀)
1     0.75            (맥주)
2     0.75           (양상추)
3     0.50            (우유)
4     0.50       (맥주, 기저귀)
5     0.50      (양상추, 기저귀)
6     0.50       (우유, 기저귀)
7     0.75       (맥주, 양상추)
8     0.50  (맥주, 양상추, 기저귀)

## FP-Growth 알고리즘

In [15]:
%%time 

from mlxtend.frequent_patterns import fpgrowth
fpgrowth(df, min_support = 0.5, use_colnames = True)

CPU times: user 5.49 ms, sys: 53 µs, total: 5.55 ms
Wall time: 4.87 ms

   support        itemsets
0     0.75           (기저귀)
1     0.50            (우유)
2     0.75           (양상추)
3     0.75            (맥주)
4     0.50       (맥주, 기저귀)
5     0.50      (양상추, 기저귀)
6     0.50  (맥주, 양상추, 기저귀)
7     0.50       (우유, 기저귀)
8     0.75       (맥주, 양상추)